---

- name: Add Calico directory
  ansible.builtin.file:
      path: /opt/kubernetes/calico
      state: directory
      mode: '0755'

- name: Download Calico operator manifest.
  ansible.builtin.get_url:
    url: "{{ calico_operator_manifest_url }}"
    dest: /opt/kubernetes/calico/
    mode: '644'

- name: Apply Calico operator manifest.
  kubernetes.core.k8s:
    state: present
    src: /opt/kubernetes/calico/calico.yaml

- name: Install calicoctl.
  ansible.builtin.get_url:
    url: "{{ calicoctl_url }}"
    dest: /usr/local/bin/calicoctl
    mode: '744'
