---

- name: Add Kubernetes repository
  block:
    - name: Kubernetes repo | apt key
      ansible.builtin.get_url:
        url: "{{ kubernetes_key_url }}"
        dest: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc
        mode: '644'

    - name: Kubernetes repo | apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
        state: present
        filename: kubernetes

- name: Install Kubernetes components
  ansible.builtin.apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: latest
    update_cache: true

- name: Prevent kubernetes components from being upgraded
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
