---

- name: Install Kubernetes and components
  hosts: k8s
  gather_facts: true
  become: true
  any_errors_fatal: true
  vars:
    master_node: k8s-0

  tasks:

    - name: Run role Prepare OS
      ansible.builtin.include_role:
        name: role-kubernetes-prepare-os

    - name: Run role Install Components
      ansible.builtin.include_role:
        name: role-kubernetes-install-components

    - name: Run role Initialize Cluster
      ansible.builtin.include_role:
        name: role-kubernetes-initialize-cluster
      when: inventory_hostname in groups['master']

    - name: Run role Install CNI
      ansible.builtin.include_role:
        name: role-kubernetes-install-cni
      when: inventory_hostname in groups['master']

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Join workers
      ansible.builtin.command: "{{ hostvars['k8s_dummy']['kubernetes_join_command'] }}"
      when: inventory_hostname in groups['node']
