---

# To override default vars, edit this file and include when running install_cluster.yml

# role-kubernetes-install-cni
calico_operator_manifest_url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/tigera-operator.yaml
calicoctl_url: https://github.com/projectcalico/calico/releases/download/v3.26.3/calicoctl-linux-amd64

# role-kubernetes-initialize-cluster
pod_network_cidr: 192.168.0.0/16

# role-kubernetes-install-components
kubernetes_version: 1.28
kubernetes_key_url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key

